### ISSUE TITLE
Infografía de Gestión de Requisitos 

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-IsaHuerta23-1#1]
[Infografía de Especificación de Requisitos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-IsaHuerta23-1/files/8057664/Infografia.de.Especificacion.de.Requisitos.pdf)

**Comment by christopheremv** [comment]
Calificación: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
